add-api-client
MrToWy/MealMaster pull request #30
Opened 2024-12-04 19:40 UTC by MrToWy

2024-12-09 07:10 UTC, MrToWy commented
- [ ] die Änderungen an der Datenbank sollten im ER-Diagramm eingetragen werden

2024-12-09 10:27 UTC, sophiefuerhoff requested changes

2024-12-09 10:27 UTC, sophiefuerhoff commented on lib/db/db_test.dart
> +import 'package:mealmaster/db/example_image.dart';
Magst du vielleicht relative imports nehmen?

2024-12-09 10:27 UTC, sophiefuerhoff commented on lib/db/meal_plan_entry.dart
>    final mealPlan = IsarLinks<MealPlan>();
Reicht hier nicht IsarLink?

2024-12-09 10:27 UTC, sophiefuerhoff commented on lib/shared/open_ai/api_client.dart
> +import 'package:mealmaster/shared/open_ai/request_body.dart';
relative

2024-12-09 10:27 UTC, sophiefuerhoff commented on lib/shared/open_ai/api_client.dart
> +                    'quantity': {
In dem StorageIngredient haben wir es immer count genannt. Sollte das vielleicht einheitlich sein?

2024-12-09 10:27 UTC, sophiefuerhoff commented on lib/shared/open_ai/request_body.dart
> +class Message {
Wären das dann nicht eigene Dateien für Message, Content und AiFunction?

2024-12-09 10:45 UTC, sophiefuerhoff commented on lib/shared/open_ai/api_client.dart
> +              final recipeIngredient = RecipeIngredient()
Vielleicht kann man hier die einzelne Schleifen in eigene Methoden tun um das lesbarerer zu machen. Ist schon sehr viel hier

2024-12-11 09:28 UTC, MrToWy commented on lib/db/meal_plan_entry.dart
>    final mealPlan = IsarLinks<MealPlan>();
#39

2024-12-11 16:32 UTC, sophiefuerhoff approved these changes

2024-12-11 16:33 UTC, merged